package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestionStatus<M extends BaseQuestionStatus<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setQuestion1Status(java.lang.Integer question1Status) {
		set("question1Status", question1Status);
	}

	public java.lang.Integer getQuestion1Status() {
		return get("question1Status");
	}

	public void setQuestion2Status(java.lang.Integer question2Status) {
		set("question2Status", question2Status);
	}

	public java.lang.Integer getQuestion2Status() {
		return get("question2Status");
	}

}
