package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setOrderId(java.lang.Integer orderId) {
		set("orderId", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("orderId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setPayTime(java.util.Date payTime) {
		set("payTime", payTime);
	}

	public java.util.Date getPayTime() {
		return get("payTime");
	}

	public void setTradeNum(java.lang.String tradeNum) {
		set("tradeNum", tradeNum);
	}

	public java.lang.String getTradeNum() {
		return get("tradeNum");
	}

	public void setPayPrice(java.math.BigDecimal payPrice) {
		set("payPrice", payPrice);
	}

	public java.math.BigDecimal getPayPrice() {
		return get("payPrice");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setExpireTime(java.lang.Long expireTime) {
		set("expireTime", expireTime);
	}

	public java.lang.Long getExpireTime() {
		return get("expireTime");
	}

}
