package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGame<M extends BaseGame<M>> extends Model<M> implements IBean {

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setGameName(java.lang.String gameName) {
		set("gameName", gameName);
	}

	public java.lang.String getGameName() {
		return get("gameName");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setGameFileName(java.lang.String gameFileName) {
		set("gameFileName", gameFileName);
	}

	public java.lang.String getGameFileName() {
		return get("gameFileName");
	}

	public void setSmallImg(java.lang.String smallImg) {
		set("smallImg", smallImg);
	}

	public java.lang.String getSmallImg() {
		return get("smallImg");
	}

	public void setBigImg(java.lang.String bigImg) {
		set("bigImg", bigImg);
	}

	public java.lang.String getBigImg() {
		return get("bigImg");
	}

	public void setBrief(java.lang.String brief) {
		set("brief", brief);
	}

	public java.lang.String getBrief() {
		return get("brief");
	}

	public void setPathName(java.lang.String pathName) {
		set("pathName", pathName);
	}

	public java.lang.String getPathName() {
		return get("pathName");
	}

	public void setBenefit(java.lang.String benefit) {
		set("benefit", benefit);
	}

	public java.lang.String getBenefit() {
		return get("benefit");
	}

}
