package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrainPrefer<M extends BaseTrainPrefer<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setIsTrack(java.lang.Integer isTrack) {
		set("isTrack", isTrack);
	}

	public java.lang.Integer getIsTrack() {
		return get("isTrack");
	}

	public void setIsEnglish(java.lang.Integer isEnglish) {
		set("isEnglish", isEnglish);
	}

	public java.lang.Integer getIsEnglish() {
		return get("isEnglish");
	}

	public void setIsColorBlind(java.lang.Integer isColorBlind) {
		set("isColorBlind", isColorBlind);
	}

	public java.lang.Integer getIsColorBlind() {
		return get("isColorBlind");
	}

	public void setClassPref(java.lang.String classPref) {
		set("classPref", classPref);
	}

	public java.lang.String getClassPref() {
		return get("classPref");
	}

}
