package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrainPlan<M extends BaseTrainPlan<M>> extends Model<M> implements IBean {

	public void setTrainPlanId(java.lang.Integer trainPlanId) {
		set("trainPlanId", trainPlanId);
	}

	public java.lang.Integer getTrainPlanId() {
		return get("trainPlanId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setPlayTimes(java.lang.Integer playTimes) {
		set("playTimes", playTimes);
	}

	public java.lang.Integer getPlayTimes() {
		return get("playTimes");
	}

	public void setTrainPlanDate(java.util.Date trainPlanDate) {
		set("trainPlanDate", trainPlanDate);
	}

	public java.util.Date getTrainPlanDate() {
		return get("trainPlanDate");
	}

	public void setWeek(java.lang.Integer week) {
		set("week", week);
	}

	public java.lang.Integer getWeek() {
		return get("week");
	}

	public void setTrainClassId(java.lang.Integer trainClassId) {
		set("trainClassId", trainClassId);
	}

	public java.lang.Integer getTrainClassId() {
		return get("trainClassId");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
