package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrainClass<M extends BaseTrainClass<M>> extends Model<M> implements IBean {

	public void setTrainClassId(java.lang.Integer trainClassId) {
		set("trainClassId", trainClassId);
	}

	public java.lang.Integer getTrainClassId() {
		return get("trainClassId");
	}

	public void setTrainClassName(java.lang.String trainClassName) {
		set("trainClassName", trainClassName);
	}

	public java.lang.String getTrainClassName() {
		return get("trainClassName");
	}

}
