package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanGame<M extends BasePlanGame<M>> extends Model<M> implements IBean {

	public void setPlanGameId(java.lang.Integer planGameId) {
		set("planGameId", planGameId);
	}

	public java.lang.Integer getPlanGameId() {
		return get("planGameId");
	}

	public void setTrainPlanId(java.lang.Integer trainPlanId) {
		set("trainPlanId", trainPlanId);
	}

	public java.lang.Integer getTrainPlanId() {
		return get("trainPlanId");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setIsPlay(java.lang.Integer isPlay) {
		set("isPlay", isPlay);
	}

	public java.lang.Integer getIsPlay() {
		return get("isPlay");
	}

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.Integer getSequence() {
		return get("sequence");
	}

}
