package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserGame<M extends BaseUserGame<M>> extends Model<M> implements IBean {

	public void setUserGameId(java.lang.Integer userGameId) {
		set("userGameId", userGameId);
	}

	public java.lang.Integer getUserGameId() {
		return get("userGameId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setIsLocked(java.lang.Integer isLocked) {
		set("isLocked", isLocked);
	}

	public java.lang.Integer getIsLocked() {
		return get("isLocked");
	}

	public void setIsLike(java.lang.Integer isLike) {
		set("isLike", isLike);
	}

	public java.lang.Integer getIsLike() {
		return get("isLike");
	}

	public void setIsPlay(java.lang.Integer isPlay) {
		set("isPlay", isPlay);
	}

	public java.lang.Integer getIsPlay() {
		return get("isPlay");
	}

	public void setLastPlayDate(java.lang.String lastPlayDate) {
		set("lastPlayDate", lastPlayDate);
	}

	public java.lang.String getLastPlayDate() {
		return get("lastPlayDate");
	}

	public void setLastPlayScore(java.lang.Integer lastPlayScore) {
		set("lastPlayScore", lastPlayScore);
	}

	public java.lang.Integer getLastPlayScore() {
		return get("lastPlayScore");
	}

	public void setLastLevel(java.lang.Integer lastLevel) {
		set("lastLevel", lastLevel);
	}

	public java.lang.Integer getLastLevel() {
		return get("lastLevel");
	}

	public void setExpire(java.util.Date expire) {
		set("expire", expire);
	}

	public java.util.Date getExpire() {
		return get("expire");
	}

	public void setBestScore(java.lang.Integer bestScore) {
		set("bestScore", bestScore);
	}

	public java.lang.Integer getBestScore() {
		return get("bestScore");
	}

	public void setBestPlayDate(java.util.Date bestPlayDate) {
		set("bestPlayDate", bestPlayDate);
	}

	public java.util.Date getBestPlayDate() {
		return get("bestPlayDate");
	}

}
