package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriceauthorsub<M extends BasePriceauthorsub<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPriceAuthorID(java.lang.Integer priceAuthorID) {
		set("priceAuthorID", priceAuthorID);
	}

	public java.lang.Integer getPriceAuthorID() {
		return get("priceAuthorID");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setOutPrice(java.math.BigDecimal outPrice) {
		set("outPrice", outPrice);
	}

	public java.math.BigDecimal getOutPrice() {
		return get("outPrice");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

}
