package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestPlan<M extends BaseTestPlan<M>> extends Model<M> implements IBean {

	public void setTestId(java.lang.Integer testId) {
		set("testId", testId);
	}

	public java.lang.Integer getTestId() {
		return get("testId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.Integer getSequence() {
		return get("sequence");
	}

	public void setIsPlay(java.lang.Integer isPlay) {
		set("isPlay", isPlay);
	}

	public java.lang.Integer getIsPlay() {
		return get("isPlay");
	}

}
