package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrainPlan<M extends BaseTrainPlan<M>> extends Model<M> implements IBean {

	public void setTrainPlanId(java.lang.Integer trainPlanId) {
		set("trainPlanId", trainPlanId);
	}

	public java.lang.Integer getTrainPlanId() {
		return get("trainPlanId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setPlayTimes(java.lang.Integer playTimes) {
		set("playTimes", playTimes);
	}

	public java.lang.Integer getPlayTimes() {
		return get("playTimes");
	}

	public void setTrainPlanDate(java.util.Date trainPlanDate) {
		set("trainPlanDate", trainPlanDate);
	}

	public java.util.Date getTrainPlanDate() {
		return get("trainPlanDate");
	}

	public void setWeek(java.lang.Integer week) {
		set("week", week);
	}

	public java.lang.Integer getWeek() {
		return get("week");
	}

}
