package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEduDegree<M extends BaseEduDegree<M>> extends Model<M> implements IBean {

	public void setEduDegreeId(java.lang.Integer eduDegreeId) {
		set("eduDegreeId", eduDegreeId);
	}

	public java.lang.Integer getEduDegreeId() {
		return get("eduDegreeId");
	}

	public void setEduDegreeName(java.lang.String eduDegreeName) {
		set("eduDegreeName", eduDegreeName);
	}

	public java.lang.String getEduDegreeName() {
		return get("eduDegreeName");
	}

}
