package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	public void setSessionId(java.lang.String sessionId) {
		set("sessionId", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("sessionId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setExpireTime(java.lang.Long expireTime) {
		set("expireTime", expireTime);
	}

	public java.lang.Long getExpireTime() {
		return get("expireTime");
	}

}
