package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriceauthorpay<M extends BasePriceauthorpay<M>> extends Model<M> implements IBean {

	public void setPriceAuthorPayNum(java.lang.Integer priceAuthorPayNum) {
		set("priceAuthorPayNum", priceAuthorPayNum);
	}

	public java.lang.Integer getPriceAuthorPayNum() {
		return get("priceAuthorPayNum");
	}

	public void setOperatorId(java.lang.Integer operatorId) {
		set("operatorId", operatorId);
	}

	public java.lang.Integer getOperatorId() {
		return get("operatorId");
	}

	public void setPriceAuthorID(java.lang.Integer priceAuthorID) {
		set("priceAuthorID", priceAuthorID);
	}

	public java.lang.Integer getPriceAuthorID() {
		return get("priceAuthorID");
	}

	public void setOrgId(java.lang.Integer orgId) {
		set("orgId", orgId);
	}

	public java.lang.Integer getOrgId() {
		return get("orgId");
	}

	public void setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
	}

	public java.lang.Integer getDeptId() {
		return get("deptId");
	}

	public void setGameUserNum(java.lang.Integer gameUserNum) {
		set("gameUserNum", gameUserNum);
	}

	public java.lang.Integer getGameUserNum() {
		return get("gameUserNum");
	}

	public void setPriceTotal(java.math.BigDecimal priceTotal) {
		set("priceTotal", priceTotal);
	}

	public java.math.BigDecimal getPriceTotal() {
		return get("priceTotal");
	}

	public void setAgentID(java.lang.Integer agentID) {
		set("agentID", agentID);
	}

	public java.lang.Integer getAgentID() {
		return get("agentID");
	}

	public void setPayPrice(java.math.BigDecimal payPrice) {
		set("payPrice", payPrice);
	}

	public java.math.BigDecimal getPayPrice() {
		return get("payPrice");
	}

	public void setPayType(java.lang.String payType) {
		set("payType", payType);
	}

	public java.lang.String getPayType() {
		return get("payType");
	}

	public void setIsAuto(java.lang.Integer isAuto) {
		set("isAuto", isAuto);
	}

	public java.lang.Integer getIsAuto() {
		return get("isAuto");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
