package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAbout<M extends BaseAbout<M>> extends Model<M> implements IBean {

	public void setAboutId(java.lang.Long aboutId) {
		set("aboutId", aboutId);
	}

	public java.lang.Long getAboutId() {
		return get("aboutId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
