package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGameClass<M extends BaseGameClass<M>> extends Model<M> implements IBean {

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setGameClassName(java.lang.String gameClassName) {
		set("gameClassName", gameClassName);
	}

	public java.lang.String getGameClassName() {
		return get("gameClassName");
	}

	public void setTrainClassId(java.lang.Integer trainClassId) {
		set("trainClassId", trainClassId);
	}

	public java.lang.Integer getTrainClassId() {
		return get("trainClassId");
	}

	public void setDis(java.lang.String dis) {
		set("dis", dis);
	}

	public java.lang.String getDis() {
		return get("dis");
	}

}
