package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

	public java.lang.Integer getGender() {
		return get("gender");
	}

	public void setEducationId(java.lang.Integer educationId) {
		set("educationId", educationId);
	}

	public java.lang.Integer getEducationId() {
		return get("educationId");
	}

	public void setJobId(java.lang.Integer jobId) {
		set("jobId", jobId);
	}

	public java.lang.Integer getJobId() {
		return get("jobId");
	}

	public void setUserImg(java.lang.String userImg) {
		set("userImg", userImg);
	}

	public java.lang.String getUserImg() {
		return get("userImg");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public void setMobileId(java.lang.String mobileId) {
		set("mobileId", mobileId);
	}

	public java.lang.String getMobileId() {
		return get("mobileId");
	}

	public void setWeixinId(java.lang.String weixinId) {
		set("weixinId", weixinId);
	}

	public java.lang.String getWeixinId() {
		return get("weixinId");
	}

	public void setExpire(java.lang.Long expire) {
		set("expire", expire);
	}

	public java.lang.Long getExpire() {
		return get("expire");
	}

	public void setRegState(java.lang.Integer regState) {
		set("regState", regState);
	}

	public java.lang.Integer getRegState() {
		return get("regState");
	}

	public void setProvinceId(java.lang.Integer provinceId) {
		set("provinceId", provinceId);
	}

	public java.lang.Integer getProvinceId() {
		return get("provinceId");
	}

	public void setCityId(java.lang.Integer cityId) {
		set("cityId", cityId);
	}

	public java.lang.Integer getCityId() {
		return get("cityId");
	}

	public void setOrgId(java.lang.Integer orgId) {
		set("orgId", orgId);
	}

	public java.lang.Integer getOrgId() {
		return get("orgId");
	}

	public void setDeptId(java.lang.Integer deptId) {
		set("deptId", deptId);
	}

	public java.lang.Integer getDeptId() {
		return get("deptId");
	}

	public void setAgented(java.lang.Integer agented) {
		set("agented", agented);
	}

	public java.lang.Integer getAgented() {
		return get("agented");
	}

}
