package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBrainClassProfile<M extends BaseBrainClassProfile<M>> extends Model<M> implements IBean {

	public void setProfileId(java.lang.Integer profileId) {
		set("profileId", profileId);
	}

	public java.lang.Integer getProfileId() {
		return get("profileId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setLPI(java.lang.Integer LPI) {
		set("LPI", LPI);
	}

	public java.lang.Integer getLPI() {
		return get("LPI");
	}

}
