package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePriceBase<M extends BasePriceBase<M>> extends Model<M> implements IBean {

	public void setPriceBaseId(java.lang.Integer priceBaseId) {
		set("priceBaseId", priceBaseId);
	}

	public java.lang.Integer getPriceBaseId() {
		return get("priceBaseId");
	}

	public void setPriceBaseType(java.lang.Integer priceBaseType) {
		set("priceBaseType", priceBaseType);
	}

	public java.lang.Integer getPriceBaseType() {
		return get("priceBaseType");
	}

	public void setBaseDetail(java.lang.String baseDetail) {
		set("baseDetail", baseDetail);
	}

	public java.lang.String getBaseDetail() {
		return get("baseDetail");
	}

	public void setTrainClassId(java.lang.Integer trainClassId) {
		set("trainClassId", trainClassId);
	}

	public java.lang.Integer getTrainClassId() {
		return get("trainClassId");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setGameDate(java.lang.Integer gameDate) {
		set("gameDate", gameDate);
	}

	public java.lang.Integer getGameDate() {
		return get("gameDate");
	}

	public void setInPrice(java.math.BigDecimal inPrice) {
		set("inPrice", inPrice);
	}

	public java.math.BigDecimal getInPrice() {
		return get("inPrice");
	}

	public void setOutPrice(java.math.BigDecimal outPrice) {
		set("outPrice", outPrice);
	}

	public java.math.BigDecimal getOutPrice() {
		return get("outPrice");
	}

	public void setOperatorID(java.lang.Integer operatorID) {
		set("operatorID", operatorID);
	}

	public java.lang.Integer getOperatorID() {
		return get("operatorID");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
