package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEducation<M extends BaseEducation<M>> extends Model<M> implements IBean {

	public void setEducationId(java.lang.Integer educationId) {
		set("educationId", educationId);
	}

	public java.lang.Integer getEducationId() {
		return get("educationId");
	}

	public void setEducationName(java.lang.String educationName) {
		set("educationName", educationName);
	}

	public java.lang.String getEducationName() {
		return get("educationName");
	}

}
