package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGame<M extends BaseGame<M>> extends Model<M> implements IBean {

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setGameName(java.lang.String gameName) {
		set("gameName", gameName);
	}

	public java.lang.String getGameName() {
		return get("gameName");
	}

	public void setGameClassId(java.lang.Integer gameClassId) {
		set("gameClassId", gameClassId);
	}

	public java.lang.Integer getGameClassId() {
		return get("gameClassId");
	}

	public void setGameFileName(java.lang.String gameFileName) {
		set("gameFileName", gameFileName);
	}

	public java.lang.String getGameFileName() {
		return get("gameFileName");
	}

	public void setSmallImg(java.lang.String smallImg) {
		set("smallImg", smallImg);
	}

	public java.lang.String getSmallImg() {
		return get("smallImg");
	}

	public void setBigImg(java.lang.String bigImg) {
		set("bigImg", bigImg);
	}

	public java.lang.String getBigImg() {
		return get("bigImg");
	}

	public void setBrief(java.lang.String brief) {
		set("brief", brief);
	}

	public java.lang.String getBrief() {
		return get("brief");
	}

	public void setPathName(java.lang.String pathName) {
		set("pathName", pathName);
	}

	public java.lang.String getPathName() {
		return get("pathName");
	}

	public void setBenefit(java.lang.String benefit) {
		set("benefit", benefit);
	}

	public java.lang.String getBenefit() {
		return get("benefit");
	}

	public void setBriefID(java.lang.Integer briefID) {
		set("briefID", briefID);
	}

	public java.lang.Integer getBriefID() {
		return get("briefID");
	}

	public void setGameState(java.lang.Integer gameState) {
		set("gameState", gameState);
	}

	public java.lang.Integer getGameState() {
		return get("gameState");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setGameBeginDate(java.util.Date gameBeginDate) {
		set("gameBeginDate", gameBeginDate);
	}

	public java.util.Date getGameBeginDate() {
		return get("gameBeginDate");
	}

	public void setGameOperateAdminId(java.lang.Integer gameOperateAdminId) {
		set("gameOperateAdminId", gameOperateAdminId);
	}

	public java.lang.Integer getGameOperateAdminId() {
		return get("gameOperateAdminId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreateAdminId(java.lang.Integer createAdminId) {
		set("createAdminId", createAdminId);
	}

	public java.lang.Integer getCreateAdminId() {
		return get("createAdminId");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdateAdminId(java.lang.Integer updateAdminId) {
		set("updateAdminId", updateAdminId);
	}

	public java.lang.Integer getUpdateAdminId() {
		return get("updateAdminId");
	}

	public void setPadGameImg(java.lang.String padGameImg) {
		set("padGameImg", padGameImg);
	}

	public java.lang.String getPadGameImg() {
		return get("padGameImg");
	}

}
