package com.lumosity.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGameHistory<M extends BaseGameHistory<M>> extends Model<M> implements IBean {

	public void setGameHistoryId(java.lang.Integer gameHistoryId) {
		set("gameHistoryId", gameHistoryId);
	}

	public java.lang.Integer getGameHistoryId() {
		return get("gameHistoryId");
	}

	public void setGameId(java.lang.Integer gameId) {
		set("gameId", gameId);
	}

	public java.lang.Integer getGameId() {
		return get("gameId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public void setPlayDate(java.util.Date playDate) {
		set("playDate", playDate);
	}

	public java.util.Date getPlayDate() {
		return get("playDate");
	}

	public void setGameLPI(java.lang.Integer gameLPI) {
		set("gameLPI", gameLPI);
	}

	public java.lang.Integer getGameLPI() {
		return get("gameLPI");
	}

	public void setGameData(java.lang.String gameData) {
		set("gameData", gameData);
	}

	public java.lang.String getGameData() {
		return get("gameData");
	}

}
