package com.lumosity.model;

import com.lumosity.model.base.BaseAbout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class About extends BaseAbout<About> {
	public static final About dao = new About();
}
