package com.lumosity.model;

import com.lumosity.model.base.BaseBrief;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brief extends BaseBrief<Brief> {
	public static final Brief dao = new Brief();
}
