package com.lumosity.model;

import java.util.Date;
import java.util.List;

import com.lumosity.model.base.BaseDayClassRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayClassRecord extends BaseDayClassRecord<DayClassRecord> {
	public static final DayClassRecord dao = new DayClassRecord();
	
	public DayClassRecord findByIdAndClassAndDate(Long id, Integer classId, Date date) {
		return findFirst("select * from day_class_record where userId =? and gameClassId=? and recordDate=?", id, classId, date);
	}
	
	public List<DayClassRecord> findByIdAndDate(Long id, Date date) {
		return find("select * from day_class_record where userId =? and recordDate=?", id, date);
	}
}
