package com.lumosity.model;

import com.lumosity.model.base.BaseEducation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Education extends BaseEducation<Education> {
	public static final Education dao = new Education();
}
