package com.lumosity.model;

import com.lumosity.model.base.BaseEduDegree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduDegree extends BaseEduDegree<EduDegree> {
	public static final EduDegree dao = new EduDegree();
}
