package com.lumosity.model;

import java.util.List;

import com.lumosity.model.base.BaseGame;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Game extends BaseGame<Game> {
	public static final Game dao = new Game();
	
	/**查询所有记录**/
	public List<Game> findAll() {
		return find("select * from game");
	}
	
	public List<Game> findByGameClassId(int gameClassId) {
		return find("select * from game where gameClassId =?", gameClassId);
		
	}
	public Game findByName(String name) {
		return findFirst("select * from game where gameFileName = ?", name);
		
	}
}
