package com.lumosity.model;

import java.util.Date;
import java.util.List;

import com.lumosity.model.base.BaseGameHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GameHistory extends BaseGameHistory<GameHistory> {
	public static final GameHistory dao = new GameHistory();
	
	/**
	 * 选择前5名的成绩
	 * @param userId
	 * @param gameId
	 * @return
	 */
	public List<GameHistory> findBestScore(Long userId, Integer gameId) {
		
		return find("select score,playDate from game_history where userId =? and gameId =? order by score desc limit 5", userId, gameId);
	}
	
	public List<GameHistory> findByIdAndDate(Long id, Date date) {
		return find("select * from game_history where userId =? and playDate =?", id, date);
	}
	
	public List<GameHistory> findByUserIdOrderByScore(Long id) {
		return find("select * from game_history where userId =? order by score desc", id);
	}
}
