package com.lumosity.model;

import com.lumosity.model.base.BaseJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Job extends BaseJob<Job> {
	public static final Job dao = new Job();
}
