package com.lumosity.model;

import com.lumosity.model.base.BasePriceBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PriceBase extends BasePriceBase<PriceBase> {
	public static final PriceBase dao = new PriceBase();
}
