package com.lumosity.model;

import com.lumosity.model.base.BasePriceauthorpay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Priceauthorpay extends BasePriceauthorpay<Priceauthorpay> {
	public static final Priceauthorpay dao = new Priceauthorpay();
}
