package com.lumosity.model;

import com.lumosity.model.base.BasePriceauthorsub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Priceauthorsub extends BasePriceauthorsub<Priceauthorsub> {
	public static final Priceauthorsub dao = new Priceauthorsub();
}
