package com.lumosity.model;

import com.lumosity.model.base.BaseQuestionStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QuestionStatus extends BaseQuestionStatus<QuestionStatus> {
	public static final QuestionStatus dao = new QuestionStatus();
}
