package com.lumosity.model;

import com.lumosity.model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	public static final Session dao = new Session();
}
