package com.lumosity.model;

import java.util.List;

import com.lumosity.model.base.BaseTestPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestPlan extends BaseTestPlan<TestPlan> {
	public static final TestPlan dao = new TestPlan();
	
	public List<TestPlan> findByUser(Long id) {
		return find("select * from test_plan where userId =? order by sequence", id);
		
	}
	public List<TestPlan> remaining(Long id) {
		return find("select testId,userId,gameId,sequence,isPlay from test_plan where userId =? and isPlay=0 order by sequence", id);
		
	}
	public TestPlan findByUserAndSquence(Long id, int sqe) {
		return findFirst("select * from test_plan where userId =? and sequence =?", id, sqe);
		
	}
	
}
