package com.lumosity.model;

import java.util.Date;

import com.lumosity.model.base.BaseTrainPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainPlan extends BaseTrainPlan<TrainPlan> {
	public static final TrainPlan dao = new TrainPlan();
	
	public TrainPlan findByIdAndDate(Long userId, Date date ) {
		return findFirst("select * from train_plan where userId =? and trainPlanDate =?", userId, date);
	}
}
