package com.lumosity.model;

import com.lumosity.model.base.BaseTrainPrefer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrainPrefer extends BaseTrainPrefer<TrainPrefer> {
	public static final TrainPrefer dao = new TrainPrefer();
}
