package com.lumosity.model;

import java.util.Date;
import java.util.List;

import com.lumosity.model.base.BaseWeekRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeekRecord extends BaseWeekRecord<WeekRecord> {
	public static final WeekRecord dao = new WeekRecord();
	
	public WeekRecord findByIdAndDate(Long id, Date date) {
		return findFirst("select * from week_record where userId =? and weekEndDate =?", id, date);
	}
	
	public List<WeekRecord> findByUser(Long id) {
		return find("select * from week_record where userId =?", id);
	}
}
